---
- name: Configure MySQL database server
  hosts: dbsrvgrp
  become: true
  vars_files:
    - vars/secrets.yml
  roles:
    - mysql

- name: Configure Tomcat application server
  hosts: appsrvgrp
  become: true
  roles:
    - tomcat

- name: Configure Nginx web server
  hosts: websrvgrp
  become: true
  roles:
    - nginx
